[package]
name = "projectable"
version = "0.1.0"
edition = "2021"

[dependencies]
ansi-to-tui = "2.0.1"
anyhow = "1.0.69"
crossbeam-channel = "0.5.7"
crossterm = "0.25"
git2 = "0.16.1"
log = "0.4.17"
notify = "5.1.0"
notify-debouncer-mini = "0.2.1"
rust_search = "2.1.0"
scopeguard = "1.1.0"
tui = "0.19.0"
tui-logger = "0.8.3"
tui-textarea = "0.2.0"
tui-tree-widget = "0.11.0"

[dev-dependencies]
assert_fs = "1.0.10"
